### ISSUE TITLE
Strange behavior for truncated variables

### ISSUE THREAD

**Issue by leorjorge** [r2evans/violinplot#2]
I have a variable that varies between 1 and -1, and the kernel density plot is drawn going beyond these limits. Is there any work around that already implemented? Would it be possible to do something like that?

**Comment by r2evans** [comment]
(Sorry for the delayed response...) Not really sure, can you provide a MWE as an example?

**Comment by leorjorge** [comment]
library(violinplot)
var <- rnorm(n = 200, mean = 1, sd = 0.2)
var[var>1] <- 1
violinplot(var~rep(c(1,2),100))

The thing is, if the variable is truncated at 1, as the example above, it would be useful to have the kernel also truncated somehow.

**Comment by r2evans** [comment]
This is related to https://stackoverflow.com/q/39554039/3358272, and is a "known thing" with density plots (both generically and with R's implementation). As the SO answer suggests, you can add arguments to `density`, such as:

```r
violinplot(var~rep(c(1,2),100), density.args=list(to=1))
```

which will provide an abrupt end to the density curve. 

![image](https://user-images.githubusercontent.com/5815808/39371665-2e69b99c-49f7-11e8-8e06-66537387374e.png)


Does that address your issue?

**Comment by leorjorge** [comment]
Oh, that perfectly solves the issue! I was hoping for a simple solution like that. 
Thank you very much!
